import Head from 'next/head'
import Nav from '../nav'
import Footer from '../footer'

function Layout( {children}:any ) {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav />
    <main className='container'>
      {children}
    </main>
    <Footer />
    </>
  )
}

export default Layout