import Head from 'next/head'
import Nav from './nav'
import Footer from './footer'

function Layout( {children}:any ) {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav />
    <div> {children} </div>
    <Footer />
    </>
  )
}

export default Layout